#!/bin/bash
echo ...........................................................
echo Loading source code
echo ...........................................................
git pull

echo ...........................................................
echo Building image
echo ...........................................................
docker build -t ghcr.io/severtech/avwx-api/avwx-api:latest .

echo ...........................................................
echo Sending image to library ghcr.io
echo ...........................................................
docker push ghcr.io/severtech/avwx-api/avwx-api:latest
echo ...........................................................
echo Loading image back from library ghcr.io to flightrf.com
echo ...........................................................
docker pull ghcr.io/severtech/avwx-api/avwx-api:latest
echo ...........................................................
echo Updating docker container on flightrf.com
echo ...........................................................
#curl -k -X POST https://flightrf.com:9443/api/webhooks/c47f70db-de4c-4c61-8a5e-54f00fe404ff
